version: "3"

services:
  router:
    build: src/Router/
    command: java Router.java gold
    networks:
      - m1

  forwarding-service:
    build: src/ForwardingService
    command: java ForwardingService.java gold
    networks:
      - m1

  tcpdump:
    image: kaazing/tcpdump
    network_mode: "host"
    volumes:
      - ./tcpdump:/tcpdump

networks:
  m1:
