version: "3"

services:
  controller:
    build: src/Controller
    command: java Controller.java

  1-router:
    image: router
    build: src/Router/
    command: java Router.java r1 r2 r3
    depends_on:
      - controller

  2-router:
    image: router
    command: java Router.java r2
    depends_on:
      - controller

  3-router:
    image: router
    command: java Router.java r3 r4
    depends_on:
      - controller

  4-router:
    image: router
    command: java Router.java r4 r5
    depends_on:
      - controller

  5-router:
    image: router
    command: java Router.java r5
    depends_on:
      - controller

  1-end:
    image: end
    build: src/EndNode/
    command: java EndNode.java a1 r1
    depends_on:
      - 1-router

  tcpdump:
    image: kaazing/tcpdump
    volumes:
      - ./tcpdump:/tcpdump
    network_mode: host
