version: "3"

services:
  controller:
    build: src/Controller
    command: java Controller.java

  1-router:
    build: src/Router/
    command: java Router.java 1 2 4
    links:
      - "1-forwarding-service:fs"
    depends_on:
      - controller
      - 2-router

  1-forwarding-service:
    build: src/ForwardingService
    command: java ForwardingService.java 1

  2-router:
    build: src/Router/
    command: java Router.java 2
    links:
      - "2-forwarding-service:fs"
    depends_on:
      - controller

  2-forwarding-service:
    build: src/ForwardingService
    command: java ForwardingService.java 2

  3-router:
    build: src/Router/
    command: java Router.java 3
    links:
      - "3-forwarding-service:fs"
    depends_on:
      - controller

  3-forwarding-service:
    build: src/ForwardingService
    command: java ForwardingService.java 3

  4-router:
    build: src/Router/
    command: java Router.java 4 3
    links:
      - "4-forwarding-service:fs"
    depends_on:
      - controller

  4-forwarding-service:
    build: src/ForwardingService
    command: java ForwardingService.java 4

  # 5-router:
  #   build: src/Router/
  #   command: java Router.java 5
  #   links:
  #     - "5-forwarding-service:fs"
  #   depends_on:
  #     - controller

  # 5-forwarding-service:
  #   build: src/ForwardingService
  #   command: java ForwardingService.java 5

  tcpdump:
    image: kaazing/tcpdump
    volumes:
      - ./tcpdump:/tcpdump
    network_mode: host
