version: "3"

services:
  controller:
    build: src/Controller
    command: java Controller.java

  1-router:
    image: router
    build: src/Router/
    command: java Router.java r1 a1 r2 r3
    depends_on:
      - controller

  2-router:
    image: router
    command: java Router.java r2 a2 r1
    depends_on:
      - controller

  3-router:
    image: router
    command: java Router.java r3 a3 r1 r4
    depends_on:
      - controller

  4-router:
    image: router
    command: java Router.java r4 r5
    depends_on:
      - controller

  5-router:
    image: router
    command: java Router.java r5
    depends_on:
      - controller

  1-end:
    image: end
    build: src/EndNode/
    command: java EndNode.java a1 r1
    depends_on:
      - 1-router

  2-end:
    image: end
    command: java EndNode.java a2 r2
    depends_on:
      - 2-router

  3-end:
    image: end
    command: java EndNode.java a3 r3
    depends_on:
      - 2-router

  tcpdump:
    image: kaazing/tcpdump
    volumes:
      - ./tcpdump:/tcpdump
    network_mode: host
