version: "3"

services:
  router:
    build: src/Router/
    command: bash -c "java Router.java 12 && java ForwardingService.java"

  node:
    build: src/Node/
    command: java Node.java
    network_mode: "host"

  tcpdump:
    image: kaazing/tcpdump
    network_mode: "host"
    volumes:
      - ./tcpdump:/tcpdump
