version: "3"

services:
  1-router:
    build: src/Router/
    command: java Router.java gold
    links:
      - "1-forwarding-service:fs"

  1-forwarding-service:
    build: src/ForwardingService
    command: java ForwardingService.java gold

  2-router:
    build: src/Router/
    command: java Router.java gold
    links:
      - "2-forwarding-service:fs"

  2-forwarding-service:
    build: src/ForwardingService
    command: java ForwardingService.java gold

  tcpdump:
    image: kaazing/tcpdump
    volumes:
      - ./tcpdump:/tcpdump
